// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fir_HH_
#define _fir_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "fir_mul_mul_16s_1bkb.h"
#include "fir_mac_muladd_10cud.h"
#include "fir_mac_muladd_16dEe.h"
#include "fir_shift_reg.h"
#include "fir_c.h"

namespace ap_rtl {

struct fir : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_lv<16> > y;
    sc_out< sc_logic > y_ap_vld;
    sc_in< sc_lv<16> > x;


    // Module declarations
    fir(sc_module_name name);
    SC_HAS_PROCESS(fir);

    ~fir();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    fir_shift_reg* shift_reg_U;
    fir_c* c_U;
    fir_mul_mul_16s_1bkb<1,1,16,10,26>* fir_mul_mul_16s_1bkb_U0;
    fir_mac_muladd_10cud<1,1,10,16,31,31>* fir_mac_muladd_10cud_U1;
    fir_mac_muladd_16dEe<1,1,16,16,37,37>* fir_mac_muladd_16dEe_U2;
    sc_signal< sc_lv<6> > shift_reg_address0;
    sc_signal< sc_logic > shift_reg_ce0;
    sc_signal< sc_logic > shift_reg_we0;
    sc_signal< sc_lv<16> > shift_reg_d0;
    sc_signal< sc_lv<16> > shift_reg_q0;
    sc_signal< sc_lv<6> > c_address0;
    sc_signal< sc_logic > c_ce0;
    sc_signal< sc_lv<16> > c_q0;
    sc_signal< sc_lv<26> > acc_fu_173_p2;
    sc_signal< sc_lv<26> > acc_reg_196;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<37> > acc_cast_fu_125_p1;
    sc_signal< sc_lv<32> > i_cast1_fu_128_p1;
    sc_signal< sc_lv<32> > i_cast1_reg_212;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<6> > i_1_fu_139_p2;
    sc_signal< sc_lv<6> > i_1_reg_220;
    sc_signal< sc_lv<1> > tmp_3_fu_133_p2;
    sc_signal< sc_lv<16> > shift_reg_load_1_reg_235;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<16> > c_load_reg_240;
    sc_signal< sc_lv<37> > grp_fu_188_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<37> > acc1_reg_100;
    sc_signal< sc_lv<6> > i_reg_110;
    sc_signal< sc_lv<32> > i_1_cast_fu_145_p1;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<31> > grp_fu_179_p3;
    sc_signal< sc_lv<10> > acc_fu_173_p1;
    sc_signal< sc_lv<10> > grp_fu_179_p0;
    sc_signal< sc_lv<31> > grp_fu_179_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<6> ap_const_lv6_39;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<6> ap_const_lv6_3F;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<26> ap_const_lv26_3FFFE86;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_acc_cast_fu_125_p1();
    void thread_acc_fu_173_p1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_c_address0();
    void thread_c_ce0();
    void thread_grp_fu_179_p0();
    void thread_grp_fu_179_p2();
    void thread_i_1_cast_fu_145_p1();
    void thread_i_1_fu_139_p2();
    void thread_i_cast1_fu_128_p1();
    void thread_shift_reg_address0();
    void thread_shift_reg_ce0();
    void thread_shift_reg_d0();
    void thread_shift_reg_we0();
    void thread_tmp_3_fu_133_p2();
    void thread_y();
    void thread_y_ap_vld();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
