// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "row_V"
#define AUTOTB_TVOUT_row_V  "../tv/cdatafile/c.leds.autotvout_row_V.dat"
// wrapc file define: "col_V"
#define AUTOTB_TVOUT_col_V  "../tv/cdatafile/c.leds.autotvout_col_V.dat"
// wrapc file define: "in_V_V"
#define AUTOTB_TVIN_in_V_V  "../tv/cdatafile/c.leds.autotvin_in_V_V.dat"
#define WRAPC_STREAM_SIZE_IN_in_V_V  "../tv/stream_size/stream_size_in_in_V_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_in_V_V  "../tv/stream_size/stream_ingress_status_in_V_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "row_V"
#define AUTOTB_TVOUT_PC_row_V  "../tv/rtldatafile/rtl.leds.autotvout_row_V.dat"
// tvout file define: "col_V"
#define AUTOTB_TVOUT_PC_col_V  "../tv/rtldatafile/rtl.leds.autotvout_col_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			row_V_depth = 0;
			col_V_depth = 0;
			in_V_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{row_V " << row_V_depth << "}\n";
			total_list << "{col_V " << col_V_depth << "}\n";
			total_list << "{in_V_V " << in_V_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int row_V_depth;
		int col_V_depth;
		int in_V_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void leds (
ap_uint<7>* row,
ap_uint<10>* col,
hls::stream<ap_uint<11> >& in);

void AESL_WRAP_leds (
ap_uint<7>* row,
ap_uint<10>* col,
hls::stream<ap_uint<11> >& in)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "in"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				in.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "row_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_row_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_row_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_row_V, AESL_token); // data

			sc_bv<7> *row_V_pc_buffer = new sc_bv<7>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'row_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'row_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					row_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_row_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_row_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: row_V
				{
					// bitslice(6, 0)
					// {
						// celement: row.V(6, 0)
						// {
							sc_lv<7>* row_V_lv0_0_0_1 = new sc_lv<7>[1];
						// }
					// }

					// bitslice(6, 0)
					{
						int hls_map_index = 0;
						// celement: row.V(6, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(row[0]) != NULL) // check the null address if the c port is array or others
								{
									row_V_lv0_0_0_1[hls_map_index].range(6, 0) = sc_bv<7>(row_V_pc_buffer[hls_map_index].range(6, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(6, 0)
					{
						int hls_map_index = 0;
						// celement: row.V(6, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : row[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : row[0]
								// output_left_conversion : row[i_0]
								// output_type_conversion : (row_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(row[0]) != NULL) // check the null address if the c port is array or others
								{
									row[i_0] = (row_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] row_V_pc_buffer;
		}

		// output port post check: "col_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_col_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_col_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_col_V, AESL_token); // data

			sc_bv<10> *col_V_pc_buffer = new sc_bv<10>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'col_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'col_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					col_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_col_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_col_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: col_V
				{
					// bitslice(9, 0)
					// {
						// celement: col.V(9, 0)
						// {
							sc_lv<10>* col_V_lv0_0_0_1 = new sc_lv<10>[1];
						// }
					// }

					// bitslice(9, 0)
					{
						int hls_map_index = 0;
						// celement: col.V(9, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(col[0]) != NULL) // check the null address if the c port is array or others
								{
									col_V_lv0_0_0_1[hls_map_index].range(9, 0) = sc_bv<10>(col_V_pc_buffer[hls_map_index].range(9, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(9, 0)
					{
						int hls_map_index = 0;
						// celement: col.V(9, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : col[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : col[0]
								// output_left_conversion : col[i_0]
								// output_type_conversion : (col_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(col[0]) != NULL) // check the null address if the c port is array or others
								{
									col[i_0] = (col_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] col_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "row_V"
		char* tvout_row_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_row_V);

		// "col_V"
		char* tvout_col_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_col_V);

		// "in_V_V"
		char* tvin_in_V_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_in_V_V);
		char* wrapc_stream_size_in_in_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_in_V_V);
		char* wrapc_stream_ingress_status_in_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_in_V_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "in"
		std::vector<ap_uint<11> > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!in.empty())
		{
			aesl_tmp_0.push_back(in.read());
			aesl_tmp_1++;
		}

		// push back input stream: "in"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			in.write(aesl_tmp_0[i]);
		}

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		leds(row, col, in);

		CodeState = DUMP_OUTPUTS;
		// record input size to tv3: "in"
		int aesl_tmp_2 = in.size();

		// [[transaction]]
		sprintf(tvout_row_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_row_V, tvout_row_V);

		sc_bv<7>* row_V_tvout_wrapc_buffer = new sc_bv<7>[1];

		// RTL Name: row_V
		{
			// bitslice(6, 0)
			{
				int hls_map_index = 0;
				// celement: row.V(6, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : row[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : row[0]
						// regulate_c_name       : row_V
						// input_type_conversion : (row[i_0]).to_string(2).c_str()
						if (&(row[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<7> row_V_tmp_mem;
							row_V_tmp_mem = (row[i_0]).to_string(2).c_str();
							row_V_tvout_wrapc_buffer[hls_map_index].range(6, 0) = row_V_tmp_mem.range(6, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_row_V, "%s\n", (row_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_row_V, tvout_row_V);
		}

		tcl_file.set_num(1, &tcl_file.row_V_depth);
		sprintf(tvout_row_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_row_V, tvout_row_V);

		// release memory allocation
		delete [] row_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_col_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_col_V, tvout_col_V);

		sc_bv<10>* col_V_tvout_wrapc_buffer = new sc_bv<10>[1];

		// RTL Name: col_V
		{
			// bitslice(9, 0)
			{
				int hls_map_index = 0;
				// celement: col.V(9, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : col[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : col[0]
						// regulate_c_name       : col_V
						// input_type_conversion : (col[i_0]).to_string(2).c_str()
						if (&(col[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<10> col_V_tmp_mem;
							col_V_tmp_mem = (col[i_0]).to_string(2).c_str();
							col_V_tvout_wrapc_buffer[hls_map_index].range(9, 0) = col_V_tmp_mem.range(9, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_col_V, "%s\n", (col_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_col_V, tvout_col_V);
		}

		tcl_file.set_num(1, &tcl_file.col_V_depth);
		sprintf(tvout_col_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_col_V, tvout_col_V);

		// release memory allocation
		delete [] col_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_in_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_in_V_V, tvin_in_V_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, tvin_in_V_V);

		sc_bv<11>* in_V_V_tvin_wrapc_buffer = new sc_bv<11>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: in_V_V
		{
			// bitslice(10, 0)
			{
				int hls_map_index = 0;
				// celement: in.V.V(10, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_0[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_0[0]
						// regulate_c_name       : in_V_V
						// input_type_conversion : (aesl_tmp_0[i_0]).to_string(2).c_str()
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<11> in_V_V_tmp_mem;
							in_V_V_tmp_mem = (aesl_tmp_0[i_0]).to_string(2).c_str();
							in_V_V_tvin_wrapc_buffer[hls_map_index].range(10, 0) = in_V_V_tmp_mem.range(10, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_in_V_V, "%s\n", (in_V_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_in_V_V, tvin_in_V_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_in_V_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, stream_ingress_size_in_V_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_in_V_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, stream_ingress_size_in_V_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.in_V_V_depth);
		sprintf(tvin_in_V_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_in_V_V, tvin_in_V_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, tvin_in_V_V);

		// release memory allocation
		delete [] in_V_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_in_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_V_V, wrapc_stream_size_in_in_V_V);
		sprintf(wrapc_stream_size_in_in_V_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_V_V, wrapc_stream_size_in_in_V_V);
		sprintf(wrapc_stream_size_in_in_V_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_V_V, wrapc_stream_size_in_in_V_V);

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "row_V"
		delete [] tvout_row_V;
		// release memory allocation: "col_V"
		delete [] tvout_col_V;
		// release memory allocation: "in_V_V"
		delete [] tvin_in_V_V;
		delete [] wrapc_stream_size_in_in_V_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

