// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct_1d2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_1d2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_1d2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> dct_1d2::ap_ST_fsm_state1 = "1";
const sc_lv<6> dct_1d2::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<6> dct_1d2::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<6> dct_1d2::ap_ST_fsm_pp0_stage2 = "1000";
const sc_lv<6> dct_1d2::ap_ST_fsm_pp0_stage3 = "10000";
const sc_lv<6> dct_1d2::ap_ST_fsm_state10 = "100000";
const bool dct_1d2::ap_const_boolean_1 = true;
const sc_lv<32> dct_1d2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dct_1d2::ap_const_lv32_2 = "10";
const bool dct_1d2::ap_const_boolean_0 = false;
const sc_lv<1> dct_1d2::ap_const_lv1_0 = "0";
const sc_lv<32> dct_1d2::ap_const_lv32_3 = "11";
const sc_lv<32> dct_1d2::ap_const_lv32_4 = "100";
const sc_lv<32> dct_1d2::ap_const_lv32_1 = "1";
const sc_lv<1> dct_1d2::ap_const_lv1_1 = "1";
const sc_lv<4> dct_1d2::ap_const_lv4_0 = "0000";
const sc_lv<3> dct_1d2::ap_const_lv3_0 = "000";
const sc_lv<7> dct_1d2::ap_const_lv7_1 = "1";
const sc_lv<25> dct_1d2::ap_const_lv25_0 = "0000000000000000000000000";
const sc_lv<7> dct_1d2::ap_const_lv7_2 = "10";
const sc_lv<7> dct_1d2::ap_const_lv7_3 = "11";
const sc_lv<7> dct_1d2::ap_const_lv7_4 = "100";
const sc_lv<7> dct_1d2::ap_const_lv7_5 = "101";
const sc_lv<7> dct_1d2::ap_const_lv7_6 = "110";
const sc_lv<7> dct_1d2::ap_const_lv7_7 = "111";
const sc_lv<4> dct_1d2::ap_const_lv4_8 = "1000";
const sc_lv<4> dct_1d2::ap_const_lv4_1 = "1";
const sc_lv<32> dct_1d2::ap_const_lv32_D = "1101";
const sc_lv<32> dct_1d2::ap_const_lv32_1C = "11100";
const sc_lv<29> dct_1d2::ap_const_lv29_1000 = "1000000000000";
const sc_lv<32> dct_1d2::ap_const_lv32_5 = "101";

dct_1d2::dct_1d2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dct_coeff_table_0_U = new dct_1d2_dct_coeffbkb("dct_coeff_table_0_U");
    dct_coeff_table_0_U->clk(ap_clk);
    dct_coeff_table_0_U->reset(ap_rst);
    dct_coeff_table_0_U->address0(dct_coeff_table_0_address0);
    dct_coeff_table_0_U->ce0(dct_coeff_table_0_ce0);
    dct_coeff_table_0_U->q0(dct_coeff_table_0_q0);
    dct_coeff_table_1_U = new dct_1d2_dct_coeffcud("dct_coeff_table_1_U");
    dct_coeff_table_1_U->clk(ap_clk);
    dct_coeff_table_1_U->reset(ap_rst);
    dct_coeff_table_1_U->address0(dct_coeff_table_1_address0);
    dct_coeff_table_1_U->ce0(dct_coeff_table_1_ce0);
    dct_coeff_table_1_U->q0(dct_coeff_table_1_q0);
    dct_coeff_table_2_U = new dct_1d2_dct_coeffdEe("dct_coeff_table_2_U");
    dct_coeff_table_2_U->clk(ap_clk);
    dct_coeff_table_2_U->reset(ap_rst);
    dct_coeff_table_2_U->address0(dct_coeff_table_2_address0);
    dct_coeff_table_2_U->ce0(dct_coeff_table_2_ce0);
    dct_coeff_table_2_U->q0(dct_coeff_table_2_q0);
    dct_coeff_table_3_U = new dct_1d2_dct_coeffeOg("dct_coeff_table_3_U");
    dct_coeff_table_3_U->clk(ap_clk);
    dct_coeff_table_3_U->reset(ap_rst);
    dct_coeff_table_3_U->address0(dct_coeff_table_3_address0);
    dct_coeff_table_3_U->ce0(dct_coeff_table_3_ce0);
    dct_coeff_table_3_U->q0(dct_coeff_table_3_q0);
    dct_coeff_table_4_U = new dct_1d2_dct_coefffYi("dct_coeff_table_4_U");
    dct_coeff_table_4_U->clk(ap_clk);
    dct_coeff_table_4_U->reset(ap_rst);
    dct_coeff_table_4_U->address0(dct_coeff_table_4_address0);
    dct_coeff_table_4_U->ce0(dct_coeff_table_4_ce0);
    dct_coeff_table_4_U->q0(dct_coeff_table_4_q0);
    dct_coeff_table_5_U = new dct_1d2_dct_coeffg8j("dct_coeff_table_5_U");
    dct_coeff_table_5_U->clk(ap_clk);
    dct_coeff_table_5_U->reset(ap_rst);
    dct_coeff_table_5_U->address0(dct_coeff_table_5_address0);
    dct_coeff_table_5_U->ce0(dct_coeff_table_5_ce0);
    dct_coeff_table_5_U->q0(dct_coeff_table_5_q0);
    dct_coeff_table_6_U = new dct_1d2_dct_coeffhbi("dct_coeff_table_6_U");
    dct_coeff_table_6_U->clk(ap_clk);
    dct_coeff_table_6_U->reset(ap_rst);
    dct_coeff_table_6_U->address0(dct_coeff_table_6_address0);
    dct_coeff_table_6_U->ce0(dct_coeff_table_6_ce0);
    dct_coeff_table_6_U->q0(dct_coeff_table_6_q0);
    dct_coeff_table_7_U = new dct_1d2_dct_coeffibs("dct_coeff_table_7_U");
    dct_coeff_table_7_U->clk(ap_clk);
    dct_coeff_table_7_U->reset(ap_rst);
    dct_coeff_table_7_U->address0(dct_coeff_table_7_address0);
    dct_coeff_table_7_U->ce0(dct_coeff_table_7_ce0);
    dct_coeff_table_7_U->q0(dct_coeff_table_7_q0);
    dct_mul_mul_16s_1jbC_U0 = new dct_mul_mul_16s_1jbC<1,1,16,15,29>("dct_mul_mul_16s_1jbC_U0");
    dct_mul_mul_16s_1jbC_U0->din0(reg_278);
    dct_mul_mul_16s_1jbC_U0->din1(dct_coeff_table_1_lo_reg_666);
    dct_mul_mul_16s_1jbC_U0->dout(tmp_7_1_fu_526_p2);
    dct_mul_mul_16s_1jbC_U1 = new dct_mul_mul_16s_1jbC<1,1,16,15,29>("dct_mul_mul_16s_1jbC_U1");
    dct_mul_mul_16s_1jbC_U1->din0(reg_282);
    dct_mul_mul_16s_1jbC_U1->din1(dct_coeff_table_3_lo_reg_671);
    dct_mul_mul_16s_1jbC_U1->dout(tmp_7_3_fu_532_p2);
    dct_mac_muladd_16kbM_U2 = new dct_mac_muladd_16kbM<1,1,16,14,29,29>("dct_mac_muladd_16kbM_U2");
    dct_mac_muladd_16kbM_U2->din0(reg_278);
    dct_mac_muladd_16kbM_U2->din1(grp_fu_538_p1);
    dct_mac_muladd_16kbM_U2->din2(tmp_7_1_reg_686);
    dct_mac_muladd_16kbM_U2->dout(grp_fu_538_p3);
    dct_mul_mul_16s_1jbC_U3 = new dct_mul_mul_16s_1jbC<1,1,16,15,29>("dct_mul_mul_16s_1jbC_U3");
    dct_mul_mul_16s_1jbC_U3->din0(reg_282);
    dct_mul_mul_16s_1jbC_U3->din1(dct_coeff_table_5_lo_reg_706);
    dct_mul_mul_16s_1jbC_U3->dout(tmp_7_5_fu_545_p2);
    dct_mac_muladd_16lbW_U4 = new dct_mac_muladd_16lbW<1,1,16,15,29,29>("dct_mac_muladd_16lbW_U4");
    dct_mac_muladd_16lbW_U4->din0(reg_278);
    dct_mac_muladd_16lbW_U4->din1(dct_coeff_table_2_lo_reg_721);
    dct_mac_muladd_16lbW_U4->din2(tmp_7_3_reg_696);
    dct_mac_muladd_16lbW_U4->dout(grp_fu_551_p3);
    dct_mac_muladd_16lbW_U5 = new dct_mac_muladd_16lbW<1,1,16,15,29,29>("dct_mac_muladd_16lbW_U5");
    dct_mac_muladd_16lbW_U5->din0(reg_282);
    dct_mac_muladd_16lbW_U5->din1(dct_coeff_table_4_lo_reg_726);
    dct_mac_muladd_16lbW_U5->din2(tmp_7_5_reg_731);
    dct_mac_muladd_16lbW_U5->dout(grp_fu_559_p3);
    dct_mac_muladd_16lbW_U6 = new dct_mac_muladd_16lbW<1,1,16,15,29,29>("dct_mac_muladd_16lbW_U6");
    dct_mac_muladd_16lbW_U6->din0(reg_278);
    dct_mac_muladd_16lbW_U6->din1(dct_coeff_table_6_lo_reg_736);
    dct_mac_muladd_16lbW_U6->din2(grp_fu_573_p3);
    dct_mac_muladd_16lbW_U6->dout(grp_fu_566_p3);
    dct_mac_muladd_16mb6_U7 = new dct_mac_muladd_16mb6<1,1,16,15,14,29>("dct_mac_muladd_16mb6_U7");
    dct_mac_muladd_16mb6_U7->din0(reg_282);
    dct_mac_muladd_16mb6_U7->din1(dct_coeff_table_7_lo_reg_741);
    dct_mac_muladd_16mb6_U7->din2(grp_fu_573_p2);
    dct_mac_muladd_16mb6_U7->dout(grp_fu_573_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage2_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage2_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage2_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage3_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage3_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage3_flag00011011);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state8_pp0_stage2_iter1);

    SC_METHOD(thread_ap_block_state9_pp0_stage3_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( tmp_fu_416_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_dct_coeff_table_0_address0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( k_cast8_reg_636 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_1_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( k_cast8_fu_428_p1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_1_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_2_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( k_cast8_reg_636 );
    sensitive << ( ap_block_pp0_stage2_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_2_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_3_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( k_cast8_fu_428_p1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_3_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_4_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( k_cast8_reg_636 );
    sensitive << ( ap_block_pp0_stage2_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_4_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_5_address0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( k_cast8_reg_636 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_5_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_6_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( k_cast8_reg_636 );
    sensitive << ( ap_block_pp0_stage2_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_6_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_flag00011001 );

    SC_METHOD(thread_dct_coeff_table_7_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( k_cast8_reg_636 );
    sensitive << ( ap_block_pp0_stage2_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_7_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_flag00011001 );

    SC_METHOD(thread_dst_address0);
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_35_cast_fu_522_p1 );
    sensitive << ( ap_block_pp0_stage3_flag00000000 );

    SC_METHOD(thread_dst_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_dst_d0);
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_5_reg_766 );
    sensitive << ( ap_block_pp0_stage3_flag00000000 );

    SC_METHOD(thread_dst_we0);
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_reg_pp0_iter1_tmp_reg_627 );

    SC_METHOD(thread_grp_fu_538_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_reg_627 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_flag00000000 );
    sensitive << ( grp_fu_538_p10 );

    SC_METHOD(thread_grp_fu_538_p10);
    sensitive << ( dct_coeff_table_0_lo_reg_681 );

    SC_METHOD(thread_grp_fu_573_p2);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_reg_pp0_iter1_tmp_reg_627 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );

    SC_METHOD(thread_k_1_fu_422_p2);
    sensitive << ( k_phi_fu_271_p4 );

    SC_METHOD(thread_k_cast8_cast_fu_434_p1);
    sensitive << ( k_phi_fu_271_p4 );

    SC_METHOD(thread_k_cast8_fu_428_p1);
    sensitive << ( k_phi_fu_271_p4 );

    SC_METHOD(thread_k_phi_fu_271_p4);
    sensitive << ( k_reg_267 );
    sensitive << ( tmp_reg_627 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( k_1_reg_631 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src_address0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( src_addr_reg_587 );
    sensitive << ( src_addr_1_reg_592 );
    sensitive << ( src_addr_2_reg_597 );
    sensitive << ( src_addr_6_reg_617 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );
    sensitive << ( ap_block_pp0_stage2_flag00000000 );
    sensitive << ( ap_block_pp0_stage3_flag00000000 );

    SC_METHOD(thread_src_address1);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( src_addr_3_reg_602 );
    sensitive << ( src_addr_4_reg_607 );
    sensitive << ( src_addr_5_reg_612 );
    sensitive << ( src_addr_7_reg_622 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );
    sensitive << ( ap_block_pp0_stage2_flag00000000 );
    sensitive << ( ap_block_pp0_stage3_flag00000000 );

    SC_METHOD(thread_src_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_src_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_tmp1_fu_485_p2);
    sensitive << ( tmp2_reg_746 );
    sensitive << ( grp_fu_551_p3 );

    SC_METHOD(thread_tmp4_fu_503_p2);
    sensitive << ( tmp5_reg_756 );
    sensitive << ( tmp6_reg_761 );

    SC_METHOD(thread_tmp_13_fu_286_p3);
    sensitive << ( i_21 );

    SC_METHOD(thread_tmp_14_fu_298_p3);
    sensitive << ( i_2 );

    SC_METHOD(thread_tmp_15_fu_306_p1);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_16_fu_311_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_17_fu_317_p3);
    sensitive << ( tmp_16_fu_311_p2 );

    SC_METHOD(thread_tmp_18_cast_fu_294_p1);
    sensitive << ( tmp_13_fu_286_p3 );

    SC_METHOD(thread_tmp_18_fu_326_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_19_fu_332_p3);
    sensitive << ( tmp_18_fu_326_p2 );

    SC_METHOD(thread_tmp_20_fu_341_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_21_fu_347_p3);
    sensitive << ( tmp_20_fu_341_p2 );

    SC_METHOD(thread_tmp_22_fu_356_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_23_fu_362_p3);
    sensitive << ( tmp_22_fu_356_p2 );

    SC_METHOD(thread_tmp_24_fu_371_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_25_fu_377_p3);
    sensitive << ( tmp_24_fu_371_p2 );

    SC_METHOD(thread_tmp_26_fu_386_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_27_fu_392_p3);
    sensitive << ( tmp_26_fu_386_p2 );

    SC_METHOD(thread_tmp_28_fu_401_p2);
    sensitive << ( tmp_14_fu_298_p3 );

    SC_METHOD(thread_tmp_29_fu_407_p3);
    sensitive << ( tmp_28_fu_401_p2 );

    SC_METHOD(thread_tmp_30_fu_438_p2);
    sensitive << ( tmp_18_cast_reg_582 );
    sensitive << ( k_cast8_cast_fu_434_p1 );

    SC_METHOD(thread_tmp_35_cast_fu_522_p1);
    sensitive << ( ap_reg_pp0_iter1_tmp_30_reg_646 );

    SC_METHOD(thread_tmp_3_fu_507_p2);
    sensitive << ( tmp1_reg_751 );
    sensitive << ( tmp4_fu_503_p2 );

    SC_METHOD(thread_tmp_fu_416_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( k_phi_fu_271_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_fu_416_p2 );
    sensitive << ( ap_block_pp0_stage0_flag00011011 );
    sensitive << ( ap_block_pp0_stage3_flag00011011 );
    sensitive << ( ap_block_pp0_stage1_flag00011011 );
    sensitive << ( ap_block_pp0_stage2_flag00011011 );

    ap_CS_fsm = "000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_1d2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_address0, "(port)src_address0");
    sc_trace(mVcdFile, src_ce0, "(port)src_ce0");
    sc_trace(mVcdFile, src_q0, "(port)src_q0");
    sc_trace(mVcdFile, src_address1, "(port)src_address1");
    sc_trace(mVcdFile, src_ce1, "(port)src_ce1");
    sc_trace(mVcdFile, src_q1, "(port)src_q1");
    sc_trace(mVcdFile, i_2, "(port)i_2");
    sc_trace(mVcdFile, dst_address0, "(port)dst_address0");
    sc_trace(mVcdFile, dst_ce0, "(port)dst_ce0");
    sc_trace(mVcdFile, dst_we0, "(port)dst_we0");
    sc_trace(mVcdFile, dst_d0, "(port)dst_d0");
    sc_trace(mVcdFile, i_21, "(port)i_21");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dct_coeff_table_0_address0, "dct_coeff_table_0_address0");
    sc_trace(mVcdFile, dct_coeff_table_0_ce0, "dct_coeff_table_0_ce0");
    sc_trace(mVcdFile, dct_coeff_table_0_q0, "dct_coeff_table_0_q0");
    sc_trace(mVcdFile, dct_coeff_table_1_address0, "dct_coeff_table_1_address0");
    sc_trace(mVcdFile, dct_coeff_table_1_ce0, "dct_coeff_table_1_ce0");
    sc_trace(mVcdFile, dct_coeff_table_1_q0, "dct_coeff_table_1_q0");
    sc_trace(mVcdFile, dct_coeff_table_2_address0, "dct_coeff_table_2_address0");
    sc_trace(mVcdFile, dct_coeff_table_2_ce0, "dct_coeff_table_2_ce0");
    sc_trace(mVcdFile, dct_coeff_table_2_q0, "dct_coeff_table_2_q0");
    sc_trace(mVcdFile, dct_coeff_table_3_address0, "dct_coeff_table_3_address0");
    sc_trace(mVcdFile, dct_coeff_table_3_ce0, "dct_coeff_table_3_ce0");
    sc_trace(mVcdFile, dct_coeff_table_3_q0, "dct_coeff_table_3_q0");
    sc_trace(mVcdFile, dct_coeff_table_4_address0, "dct_coeff_table_4_address0");
    sc_trace(mVcdFile, dct_coeff_table_4_ce0, "dct_coeff_table_4_ce0");
    sc_trace(mVcdFile, dct_coeff_table_4_q0, "dct_coeff_table_4_q0");
    sc_trace(mVcdFile, dct_coeff_table_5_address0, "dct_coeff_table_5_address0");
    sc_trace(mVcdFile, dct_coeff_table_5_ce0, "dct_coeff_table_5_ce0");
    sc_trace(mVcdFile, dct_coeff_table_5_q0, "dct_coeff_table_5_q0");
    sc_trace(mVcdFile, dct_coeff_table_6_address0, "dct_coeff_table_6_address0");
    sc_trace(mVcdFile, dct_coeff_table_6_ce0, "dct_coeff_table_6_ce0");
    sc_trace(mVcdFile, dct_coeff_table_6_q0, "dct_coeff_table_6_q0");
    sc_trace(mVcdFile, dct_coeff_table_7_address0, "dct_coeff_table_7_address0");
    sc_trace(mVcdFile, dct_coeff_table_7_ce0, "dct_coeff_table_7_ce0");
    sc_trace(mVcdFile, dct_coeff_table_7_q0, "dct_coeff_table_7_q0");
    sc_trace(mVcdFile, k_reg_267, "k_reg_267");
    sc_trace(mVcdFile, reg_278, "reg_278");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter1, "ap_block_state7_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00011001, "ap_block_pp0_stage1_flag00011001");
    sc_trace(mVcdFile, tmp_reg_627, "tmp_reg_627");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage2_iter0, "ap_block_state4_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage2_iter1, "ap_block_state8_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_flag00011001, "ap_block_pp0_stage2_flag00011001");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage3_iter0, "ap_block_state5_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage3_iter1, "ap_block_state9_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_flag00011001, "ap_block_pp0_stage3_flag00011001");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011001, "ap_block_pp0_stage0_flag00011001");
    sc_trace(mVcdFile, reg_282, "reg_282");
    sc_trace(mVcdFile, tmp_18_cast_fu_294_p1, "tmp_18_cast_fu_294_p1");
    sc_trace(mVcdFile, tmp_18_cast_reg_582, "tmp_18_cast_reg_582");
    sc_trace(mVcdFile, src_addr_reg_587, "src_addr_reg_587");
    sc_trace(mVcdFile, src_addr_1_reg_592, "src_addr_1_reg_592");
    sc_trace(mVcdFile, src_addr_2_reg_597, "src_addr_2_reg_597");
    sc_trace(mVcdFile, src_addr_3_reg_602, "src_addr_3_reg_602");
    sc_trace(mVcdFile, src_addr_4_reg_607, "src_addr_4_reg_607");
    sc_trace(mVcdFile, src_addr_5_reg_612, "src_addr_5_reg_612");
    sc_trace(mVcdFile, src_addr_6_reg_617, "src_addr_6_reg_617");
    sc_trace(mVcdFile, src_addr_7_reg_622, "src_addr_7_reg_622");
    sc_trace(mVcdFile, tmp_fu_416_p2, "tmp_fu_416_p2");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_reg_627, "ap_reg_pp0_iter1_tmp_reg_627");
    sc_trace(mVcdFile, k_1_fu_422_p2, "k_1_fu_422_p2");
    sc_trace(mVcdFile, k_1_reg_631, "k_1_reg_631");
    sc_trace(mVcdFile, k_cast8_fu_428_p1, "k_cast8_fu_428_p1");
    sc_trace(mVcdFile, k_cast8_reg_636, "k_cast8_reg_636");
    sc_trace(mVcdFile, tmp_30_fu_438_p2, "tmp_30_fu_438_p2");
    sc_trace(mVcdFile, tmp_30_reg_646, "tmp_30_reg_646");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_30_reg_646, "ap_reg_pp0_iter1_tmp_30_reg_646");
    sc_trace(mVcdFile, dct_coeff_table_1_lo_reg_666, "dct_coeff_table_1_lo_reg_666");
    sc_trace(mVcdFile, dct_coeff_table_3_lo_reg_671, "dct_coeff_table_3_lo_reg_671");
    sc_trace(mVcdFile, dct_coeff_table_0_lo_reg_681, "dct_coeff_table_0_lo_reg_681");
    sc_trace(mVcdFile, tmp_7_1_fu_526_p2, "tmp_7_1_fu_526_p2");
    sc_trace(mVcdFile, tmp_7_1_reg_686, "tmp_7_1_reg_686");
    sc_trace(mVcdFile, tmp_7_3_fu_532_p2, "tmp_7_3_fu_532_p2");
    sc_trace(mVcdFile, tmp_7_3_reg_696, "tmp_7_3_reg_696");
    sc_trace(mVcdFile, dct_coeff_table_5_lo_reg_706, "dct_coeff_table_5_lo_reg_706");
    sc_trace(mVcdFile, dct_coeff_table_2_lo_reg_721, "dct_coeff_table_2_lo_reg_721");
    sc_trace(mVcdFile, dct_coeff_table_4_lo_reg_726, "dct_coeff_table_4_lo_reg_726");
    sc_trace(mVcdFile, tmp_7_5_fu_545_p2, "tmp_7_5_fu_545_p2");
    sc_trace(mVcdFile, tmp_7_5_reg_731, "tmp_7_5_reg_731");
    sc_trace(mVcdFile, dct_coeff_table_6_lo_reg_736, "dct_coeff_table_6_lo_reg_736");
    sc_trace(mVcdFile, dct_coeff_table_7_lo_reg_741, "dct_coeff_table_7_lo_reg_741");
    sc_trace(mVcdFile, grp_fu_538_p3, "grp_fu_538_p3");
    sc_trace(mVcdFile, tmp2_reg_746, "tmp2_reg_746");
    sc_trace(mVcdFile, tmp1_fu_485_p2, "tmp1_fu_485_p2");
    sc_trace(mVcdFile, tmp1_reg_751, "tmp1_reg_751");
    sc_trace(mVcdFile, grp_fu_559_p3, "grp_fu_559_p3");
    sc_trace(mVcdFile, tmp5_reg_756, "tmp5_reg_756");
    sc_trace(mVcdFile, grp_fu_566_p3, "grp_fu_566_p3");
    sc_trace(mVcdFile, tmp6_reg_761, "tmp6_reg_761");
    sc_trace(mVcdFile, tmp_5_reg_766, "tmp_5_reg_766");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011011, "ap_block_pp0_stage0_flag00011011");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage3_flag00011011, "ap_block_pp0_stage3_flag00011011");
    sc_trace(mVcdFile, k_phi_fu_271_p4, "k_phi_fu_271_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00000000, "ap_block_pp0_stage0_flag00000000");
    sc_trace(mVcdFile, tmp_15_fu_306_p1, "tmp_15_fu_306_p1");
    sc_trace(mVcdFile, tmp_17_fu_317_p3, "tmp_17_fu_317_p3");
    sc_trace(mVcdFile, tmp_19_fu_332_p3, "tmp_19_fu_332_p3");
    sc_trace(mVcdFile, tmp_21_fu_347_p3, "tmp_21_fu_347_p3");
    sc_trace(mVcdFile, tmp_23_fu_362_p3, "tmp_23_fu_362_p3");
    sc_trace(mVcdFile, tmp_25_fu_377_p3, "tmp_25_fu_377_p3");
    sc_trace(mVcdFile, tmp_27_fu_392_p3, "tmp_27_fu_392_p3");
    sc_trace(mVcdFile, tmp_29_fu_407_p3, "tmp_29_fu_407_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00000000, "ap_block_pp0_stage1_flag00000000");
    sc_trace(mVcdFile, ap_block_pp0_stage2_flag00000000, "ap_block_pp0_stage2_flag00000000");
    sc_trace(mVcdFile, tmp_35_cast_fu_522_p1, "tmp_35_cast_fu_522_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_flag00000000, "ap_block_pp0_stage3_flag00000000");
    sc_trace(mVcdFile, tmp_13_fu_286_p3, "tmp_13_fu_286_p3");
    sc_trace(mVcdFile, tmp_14_fu_298_p3, "tmp_14_fu_298_p3");
    sc_trace(mVcdFile, tmp_16_fu_311_p2, "tmp_16_fu_311_p2");
    sc_trace(mVcdFile, tmp_18_fu_326_p2, "tmp_18_fu_326_p2");
    sc_trace(mVcdFile, tmp_20_fu_341_p2, "tmp_20_fu_341_p2");
    sc_trace(mVcdFile, tmp_22_fu_356_p2, "tmp_22_fu_356_p2");
    sc_trace(mVcdFile, tmp_24_fu_371_p2, "tmp_24_fu_371_p2");
    sc_trace(mVcdFile, tmp_26_fu_386_p2, "tmp_26_fu_386_p2");
    sc_trace(mVcdFile, tmp_28_fu_401_p2, "tmp_28_fu_401_p2");
    sc_trace(mVcdFile, k_cast8_cast_fu_434_p1, "k_cast8_cast_fu_434_p1");
    sc_trace(mVcdFile, grp_fu_551_p3, "grp_fu_551_p3");
    sc_trace(mVcdFile, tmp4_fu_503_p2, "tmp4_fu_503_p2");
    sc_trace(mVcdFile, tmp_3_fu_507_p2, "tmp_3_fu_507_p2");
    sc_trace(mVcdFile, grp_fu_538_p1, "grp_fu_538_p1");
    sc_trace(mVcdFile, grp_fu_573_p3, "grp_fu_573_p3");
    sc_trace(mVcdFile, grp_fu_573_p2, "grp_fu_573_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00011011, "ap_block_pp0_stage1_flag00011011");
    sc_trace(mVcdFile, ap_block_pp0_stage2_flag00011011, "ap_block_pp0_stage2_flag00011011");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_538_p10, "grp_fu_538_p10");
#endif

    }
}

dct_1d2::~dct_1d2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dct_coeff_table_0_U;
    delete dct_coeff_table_1_U;
    delete dct_coeff_table_2_U;
    delete dct_coeff_table_3_U;
    delete dct_coeff_table_4_U;
    delete dct_coeff_table_5_U;
    delete dct_coeff_table_6_U;
    delete dct_coeff_table_7_U;
    delete dct_mul_mul_16s_1jbC_U0;
    delete dct_mul_mul_16s_1jbC_U1;
    delete dct_mac_muladd_16kbM_U2;
    delete dct_mul_mul_16s_1jbC_U3;
    delete dct_mac_muladd_16lbW_U4;
    delete dct_mac_muladd_16lbW_U5;
    delete dct_mac_muladd_16lbW_U6;
    delete dct_mac_muladd_16mb6_U7;
}

void dct_1d2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011011.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011011.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        k_reg_267 = k_1_reg_631.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_reg_267 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_tmp_30_reg_646 = tmp_30_reg_646.read();
        ap_reg_pp0_iter1_tmp_reg_627 = tmp_reg_627.read();
        tmp_reg_627 = tmp_fu_416_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_0_lo_reg_681 = dct_coeff_table_0_q0.read();
        dct_coeff_table_5_lo_reg_706 = dct_coeff_table_5_q0.read();
        tmp_7_1_reg_686 = tmp_7_1_fu_526_p2.read();
        tmp_7_3_reg_696 = tmp_7_3_fu_532_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0))) {
        dct_coeff_table_1_lo_reg_666 = dct_coeff_table_1_q0.read();
        dct_coeff_table_3_lo_reg_671 = dct_coeff_table_3_q0.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_2_lo_reg_721 = dct_coeff_table_2_q0.read();
        dct_coeff_table_4_lo_reg_726 = dct_coeff_table_4_q0.read();
        dct_coeff_table_6_lo_reg_736 = dct_coeff_table_6_q0.read();
        dct_coeff_table_7_lo_reg_741 = dct_coeff_table_7_q0.read();
        tmp_7_5_reg_731 = tmp_7_5_fu_545_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        k_1_reg_631 = k_1_fu_422_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_416_p2.read()))) {
        k_cast8_reg_636 = k_cast8_fu_428_p1.read();
        tmp_30_reg_646 = tmp_30_fu_438_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0)))) {
        reg_278 = src_q0.read();
        reg_282 = src_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        src_addr_1_reg_592 =  (sc_lv<6>) (tmp_17_fu_317_p3.read());
        src_addr_2_reg_597 =  (sc_lv<6>) (tmp_19_fu_332_p3.read());
        src_addr_3_reg_602 =  (sc_lv<6>) (tmp_21_fu_347_p3.read());
        src_addr_4_reg_607 =  (sc_lv<6>) (tmp_23_fu_362_p3.read());
        src_addr_5_reg_612 =  (sc_lv<6>) (tmp_25_fu_377_p3.read());
        src_addr_6_reg_617 =  (sc_lv<6>) (tmp_27_fu_392_p3.read());
        src_addr_7_reg_622 =  (sc_lv<6>) (tmp_29_fu_407_p3.read());
        src_addr_reg_587 =  (sc_lv<6>) (tmp_15_fu_306_p1.read());
        tmp_18_cast_reg_582 = tmp_18_cast_fu_294_p1.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        tmp1_reg_751 = tmp1_fu_485_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0))) {
        tmp2_reg_746 = grp_fu_538_p3.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        tmp5_reg_756 = grp_fu_559_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_tmp_reg_627.read()))) {
        tmp6_reg_761 = grp_fu_566_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_tmp_reg_627.read()))) {
        tmp_5_reg_766 = tmp_3_fu_507_p2.read().range(28, 13);
    }
}

void dct_1d2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dct_1d2::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void dct_1d2::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[3];
}

void dct_1d2::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[4];
}

void dct_1d2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dct_1d2::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[5];
}

void dct_1d2::thread_ap_block_pp0_stage0_flag00000000() {
    ap_block_pp0_stage0_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage0_flag00011001() {
    ap_block_pp0_stage0_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage0_flag00011011() {
    ap_block_pp0_stage0_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage1_flag00000000() {
    ap_block_pp0_stage1_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage1_flag00011001() {
    ap_block_pp0_stage1_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage1_flag00011011() {
    ap_block_pp0_stage1_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage2_flag00000000() {
    ap_block_pp0_stage2_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage2_flag00011001() {
    ap_block_pp0_stage2_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage2_flag00011011() {
    ap_block_pp0_stage2_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage3_flag00000000() {
    ap_block_pp0_stage3_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage3_flag00011001() {
    ap_block_pp0_stage3_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage3_flag00011011() {
    ap_block_pp0_stage3_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state4_pp0_stage2_iter0() {
    ap_block_state4_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state5_pp0_stage3_iter0() {
    ap_block_state5_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state7_pp0_stage1_iter1() {
    ap_block_state7_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state8_pp0_stage2_iter1() {
    ap_block_state8_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state9_pp0_stage3_iter1() {
    ap_block_state9_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(tmp_fu_416_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dct_1d2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_0_address0() {
    dct_coeff_table_0_address0 =  (sc_lv<3>) (k_cast8_reg_636.read());
}

void dct_1d2::thread_dct_coeff_table_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_0_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_0_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_1_address0() {
    dct_coeff_table_1_address0 =  (sc_lv<3>) (k_cast8_fu_428_p1.read());
}

void dct_1d2::thread_dct_coeff_table_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_1_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_1_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_2_address0() {
    dct_coeff_table_2_address0 =  (sc_lv<3>) (k_cast8_reg_636.read());
}

void dct_1d2::thread_dct_coeff_table_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_2_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_2_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_3_address0() {
    dct_coeff_table_3_address0 =  (sc_lv<3>) (k_cast8_fu_428_p1.read());
}

void dct_1d2::thread_dct_coeff_table_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_3_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_3_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_4_address0() {
    dct_coeff_table_4_address0 =  (sc_lv<3>) (k_cast8_reg_636.read());
}

void dct_1d2::thread_dct_coeff_table_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_4_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_4_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_5_address0() {
    dct_coeff_table_5_address0 =  (sc_lv<3>) (k_cast8_reg_636.read());
}

void dct_1d2::thread_dct_coeff_table_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_5_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_5_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_6_address0() {
    dct_coeff_table_6_address0 =  (sc_lv<3>) (k_cast8_reg_636.read());
}

void dct_1d2::thread_dct_coeff_table_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_6_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_6_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_7_address0() {
    dct_coeff_table_7_address0 =  (sc_lv<3>) (k_cast8_reg_636.read());
}

void dct_1d2::thread_dct_coeff_table_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0))) {
        dct_coeff_table_7_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_7_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dst_address0() {
    dst_address0 =  (sc_lv<6>) (tmp_35_cast_fu_522_p1.read());
}

void dct_1d2::thread_dst_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dst_ce0 = ap_const_logic_1;
    } else {
        dst_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dst_d0() {
    dst_d0 = tmp_5_reg_766.read();
}

void dct_1d2::thread_dst_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_tmp_reg_627.read()))) {
        dst_we0 = ap_const_logic_1;
    } else {
        dst_we0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_grp_fu_538_p1() {
    grp_fu_538_p1 =  (sc_lv<14>) (grp_fu_538_p10.read());
}

void dct_1d2::thread_grp_fu_538_p10() {
    grp_fu_538_p10 = esl_zext<29,14>(dct_coeff_table_0_lo_reg_681.read());
}

void dct_1d2::thread_grp_fu_573_p2() {
    grp_fu_573_p2 =  (sc_lv<14>) (ap_const_lv29_1000);
}

void dct_1d2::thread_k_1_fu_422_p2() {
    k_1_fu_422_p2 = (!k_phi_fu_271_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_phi_fu_271_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_1d2::thread_k_cast8_cast_fu_434_p1() {
    k_cast8_cast_fu_434_p1 = esl_zext<8,4>(k_phi_fu_271_p4.read());
}

void dct_1d2::thread_k_cast8_fu_428_p1() {
    k_cast8_fu_428_p1 = esl_zext<32,4>(k_phi_fu_271_p4.read());
}

void dct_1d2::thread_k_phi_fu_271_p4() {
    if ((esl_seteq<1,1,1>(tmp_reg_627.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
        k_phi_fu_271_p4 = k_1_reg_631.read();
    } else {
        k_phi_fu_271_p4 = k_reg_267.read();
    }
}

void dct_1d2::thread_src_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00000000.read(), ap_const_boolean_0))) {
            src_address0 = src_addr_6_reg_617.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00000000.read(), ap_const_boolean_0))) {
            src_address0 = src_addr_2_reg_597.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00000000.read(), ap_const_boolean_0))) {
            src_address0 = src_addr_reg_587.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
            src_address0 = src_addr_1_reg_592.read();
        } else {
            src_address0 = "XXXXXX";
        }
    } else {
        src_address0 = "XXXXXX";
    }
}

void dct_1d2::thread_src_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00000000.read(), ap_const_boolean_0))) {
            src_address1 = src_addr_7_reg_622.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00000000.read(), ap_const_boolean_0))) {
            src_address1 = src_addr_4_reg_607.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00000000.read(), ap_const_boolean_0))) {
            src_address1 = src_addr_5_reg_612.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
            src_address1 = src_addr_3_reg_602.read();
        } else {
            src_address1 = "XXXXXX";
        }
    } else {
        src_address1 = "XXXXXX";
    }
}

void dct_1d2::thread_src_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0)))) {
        src_ce0 = ap_const_logic_1;
    } else {
        src_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_src_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0)))) {
        src_ce1 = ap_const_logic_1;
    } else {
        src_ce1 = ap_const_logic_0;
    }
}

void dct_1d2::thread_tmp1_fu_485_p2() {
    tmp1_fu_485_p2 = (!tmp2_reg_746.read().is_01() || !grp_fu_551_p3.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp2_reg_746.read()) + sc_bigint<29>(grp_fu_551_p3.read()));
}

void dct_1d2::thread_tmp4_fu_503_p2() {
    tmp4_fu_503_p2 = (!tmp5_reg_756.read().is_01() || !tmp6_reg_761.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp5_reg_756.read()) + sc_bigint<29>(tmp6_reg_761.read()));
}

void dct_1d2::thread_tmp_13_fu_286_p3() {
    tmp_13_fu_286_p3 = esl_concat<4,3>(i_21.read(), ap_const_lv3_0);
}

void dct_1d2::thread_tmp_14_fu_298_p3() {
    tmp_14_fu_298_p3 = esl_concat<4,3>(i_2.read(), ap_const_lv3_0);
}

void dct_1d2::thread_tmp_15_fu_306_p1() {
    tmp_15_fu_306_p1 = esl_zext<32,7>(tmp_14_fu_298_p3.read());
}

void dct_1d2::thread_tmp_16_fu_311_p2() {
    tmp_16_fu_311_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_1);
}

void dct_1d2::thread_tmp_17_fu_317_p3() {
    tmp_17_fu_317_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_16_fu_311_p2.read());
}

void dct_1d2::thread_tmp_18_cast_fu_294_p1() {
    tmp_18_cast_fu_294_p1 = esl_zext<8,7>(tmp_13_fu_286_p3.read());
}

void dct_1d2::thread_tmp_18_fu_326_p2() {
    tmp_18_fu_326_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_2);
}

void dct_1d2::thread_tmp_19_fu_332_p3() {
    tmp_19_fu_332_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_18_fu_326_p2.read());
}

void dct_1d2::thread_tmp_20_fu_341_p2() {
    tmp_20_fu_341_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_3);
}

void dct_1d2::thread_tmp_21_fu_347_p3() {
    tmp_21_fu_347_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_20_fu_341_p2.read());
}

void dct_1d2::thread_tmp_22_fu_356_p2() {
    tmp_22_fu_356_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_4);
}

void dct_1d2::thread_tmp_23_fu_362_p3() {
    tmp_23_fu_362_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_22_fu_356_p2.read());
}

void dct_1d2::thread_tmp_24_fu_371_p2() {
    tmp_24_fu_371_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_5);
}

void dct_1d2::thread_tmp_25_fu_377_p3() {
    tmp_25_fu_377_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_24_fu_371_p2.read());
}

void dct_1d2::thread_tmp_26_fu_386_p2() {
    tmp_26_fu_386_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_6);
}

void dct_1d2::thread_tmp_27_fu_392_p3() {
    tmp_27_fu_392_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_26_fu_386_p2.read());
}

void dct_1d2::thread_tmp_28_fu_401_p2() {
    tmp_28_fu_401_p2 = (tmp_14_fu_298_p3.read() | ap_const_lv7_7);
}

void dct_1d2::thread_tmp_29_fu_407_p3() {
    tmp_29_fu_407_p3 = esl_concat<25,7>(ap_const_lv25_0, tmp_28_fu_401_p2.read());
}

void dct_1d2::thread_tmp_30_fu_438_p2() {
    tmp_30_fu_438_p2 = (!tmp_18_cast_reg_582.read().is_01() || !k_cast8_cast_fu_434_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_18_cast_reg_582.read()) + sc_biguint<8>(k_cast8_cast_fu_434_p1.read()));
}

void dct_1d2::thread_tmp_35_cast_fu_522_p1() {
    tmp_35_cast_fu_522_p1 = esl_zext<32,8>(ap_reg_pp0_iter1_tmp_30_reg_646.read());
}

void dct_1d2::thread_tmp_3_fu_507_p2() {
    tmp_3_fu_507_p2 = (!tmp1_reg_751.read().is_01() || !tmp4_fu_503_p2.read().is_01())? sc_lv<29>(): (sc_biguint<29>(tmp1_reg_751.read()) + sc_biguint<29>(tmp4_fu_503_p2.read()));
}

void dct_1d2::thread_tmp_fu_416_p2() {
    tmp_fu_416_p2 = (!k_phi_fu_271_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_phi_fu_271_p4.read() == ap_const_lv4_8);
}

void dct_1d2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_fu_416_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_fu_416_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011011.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

